### ISSUE TITLE
Python 3 compatibility in crosswalk.py, search-terms.py, walk-hierarchy.py

### ISSUE THREAD

**Issue by jonathanbona** [HHS/uts-rest-api#17]
crosswalk.py, search-terms.py and walk-hierarchy.py are not python 3 compatible
I fixed these in a fork and verified they work in both python 2 and python 3 as of this commit: https://github.com/jonathanbona/uts-rest-api/commit/d062de1ae3034b17bae7307eb2a0c6a3206382c5

Pull request: https://github.com/HHS/uts-rest-api/pull/16

**Comment by stevenemrick** [comment]
merged pull request #16 into master
