### ISSUE TITLE
Please post the RMD document instead of the HTML output for the R example

### ISSUE THREAD

**Issue by jamiebono** [HHS/uts-rest-api#20]
Please post the RMD document instead of the HTML output for the R example. Thank you!

**Comment by danizen** [comment]
You may wish to take a look at https://github.com/danizen/nlm-demo-notebook/blob/master/notebooks/UTS%20Authorization%20and%20Calling%20-%20R.ipynb.   I am an NLM staffer and I'm attempting to become a committer on this repo.   The link I pointed you to is not official NLM output.
