### ISSUE TITLE
Searching UMLS current version with old concepts when using retrieve-cui-or-code or search-terms.py

### ISSUE THREAD

**Issue by beazerj** [HHS/uts-rest-api#25]
When i use the online interface to search for the concept  - C0043096, it returns the concept C1262477 as a result. It seems that C0043096 was the same concept in the 2013-2015 versions but it was changed moving forward. However, while i get a result searching for C1262477 with the version set to current in the above scripts for the api, i do not get any result for C0043096. Is there any way to search using an old concept and have the new concept show up without lopping through all the old versions?

**Comment by danizen** [comment]
I will ask about this.  I don't believe so - I maintain MeSH RDF, and all we get is the changes to update.

**Comment by beazerj** [comment]
Thanks for your help. Just to make sure the specific example is clear:

I get this for C1262477: 

python search-terms.py -k "key -s C1262477
Results for page 1

ui: C1262477
uri: https://uts-ws.nlm.nih.gov/rest/content/2019AB/CUI/C1262477
name: Weight decreased
Source Vocabulary: MTH


*********

But this for C0043096:

python search-terms.py -k "key" -s "C0043096"
Results for page 1

ui: NONE
name: NO RESULTS

see image of interface search: 

<img width="1148" alt="Screen Shot 2019-11-05 at 1 35 20 PM" src="https://user-images.githubusercontent.com/54033230/68235404-2ecdd580-ffd1-11e9-8760-73394ea8a055.png">
