### ISSUE TITLE
Searching UMLS using searchType approximate always returns CUIs

### ISSUE THREAD

**Issue by dmathisen-nextech** [HHS/uts-rest-api#35]
Making a query such as https://uts-ws.nlm.nih.gov/rest/search/current?string=cold&searchType=approximate&inputType=sourceUi&sabs=SNOMEDCT_US&pageSize=256&returnIdType=sourceUi&ticket={{singleUseTicket}} always has the CUI in the return. I've tried returnIdType of code, sourceConcept, sourceDescriptor, and sourceUi but none of those returns the source ID.

Note the following query works as expected (only difference is searchType is words): https://uts-ws.nlm.nih.gov/rest/search/current?string=cold&searchType=words&inputType=sourceUi&sabs=SNOMEDCT_US&pageSize=256&returnIdType=sourceUi&ticket={{singleUseTicket}}

**Comment by danizen** [comment]
@dmathisen-nextech , please take this issue to https://support.nlm.nih.gov/, click on "write to the help desk", and submit your issue that way.  I don't write the code for this directly, so I have to just tell you to submit a ticket elsewhere.  It seems friendlier than just removing issues from this repository.
