### ISSUE TITLE
Changing ValueError to KeyError

### ISSUE THREAD

**Issue by azarpira** [HHS/uts-rest-api#39]
https://github.com/HHS/uts-rest-api/blob/791696c1a822140c1c1332d8ac7f33d2851d28eb/samples/python/crosswalk.py#L53

Hello, 
While running this code on my macbook pro mid-2010 with IDLE 3.9.5 and python 3.9.5 ,  A 'key error' was produced.
Changing 'ValueError' to 'KeyError' at line 53 solves the error.

With best regards.

**Comment by danizen** [comment]
Thanks, we will adjust and decide what versions of Python this should work with.
